run:
  timeout: 5m
  go: '1.22'
  tests: true
  skip-dirs:
    - vendor
    - third_party

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional useful linters
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gofmt
    - goimports
    - gocritic
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - prealloc
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/otelguard/otelguard

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam
      - rangeValCopy

  gosec:
    excludes:
      - G104 # Audit errors not checked (we use errcheck for this)
      - G304 # File path provided as taint input (we handle this explicitly)

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  exhaustive:
    default-signifies-exhaustive: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic
    # Exclude main.go from some checks
    - path: cmd/server/main\.go
      linters:
        - noctx
    # Allow unused parameters in handler functions
    - path: internal/api/handlers/
      linters:
        - unparam

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
