// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/otelguard/otelguard/internal/config"
	"github.com/otelguard/otelguard/internal/wire"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// InitializeApplication creates a fully-wired Application instance.
// Wire will generate the implementation of this function.
func InitializeApplication(cfg *config.Config) (*wire.Application, error) {
	logger := wire.ProvideLogger(cfg)
	postgresDB, err := wire.ProvidePostgresDB(cfg)
	if err != nil {
		return nil, err
	}
	clickHouseDB, err := wire.ProvideClickHouseConn(cfg)
	if err != nil {
		return nil, err
	}
	db := postgresDB.DB
	healthHandler := wire.ProvideHealthHandler(db, logger)
	userRepository := wire.ProvideUserRepository(db)
	authService := wire.ProvideAuthService(userRepository, logger, cfg)
	authHandler := wire.ProvideAuthHandler(authService, cfg, logger)
	organizationRepository := wire.ProvideOrganizationRepository(db)
	projectRepository := wire.ProvideProjectRepository(db)
	orgService := wire.ProvideOrgService(organizationRepository, projectRepository, userRepository, logger, cfg)
	orgHandler := wire.ProvideOrgHandler(orgService, logger)
	conn := clickHouseDB.Conn
	traceRepository := wire.ProvideTraceRepository(conn)
	batchWriterResult := wire.ProvideBatchWriter(conn, cfg, logger)
	samplerConfig := wire.ProvideSamplerConfig(cfg)
	traceService := wire.ProvideTraceService(traceRepository, batchWriterResult, samplerConfig, cfg, logger)
	traceHandler := wire.ProvideTraceHandler(traceService, logger)
	otlpHandler := wire.ProvideOTLPHandler(traceService, logger)
	promptRepository := wire.ProvidePromptRepository(db)
	promptService := wire.ProvidePromptService(promptRepository, logger)
	promptHandler := wire.ProvidePromptHandler(promptService, logger)
	guardrailRepository := wire.ProvideGuardrailRepository(db)
	guardrailEventRepository := wire.ProvideGuardrailEventRepository(conn)
	guardrailService := wire.ProvideGuardrailService(guardrailRepository, guardrailEventRepository, logger)
	guardrailHandler := wire.ProvideGuardrailHandler(guardrailService, logger)
	handlers := wire.ProvideHandlers(healthHandler, authHandler, orgHandler, traceHandler, otlpHandler, promptHandler, guardrailHandler)
	engine := wire.ProvideRouter(handlers, cfg, logger)
	grpcComponents := wire.ProvideGRPCComponents(traceService, cfg, logger)
	application := wire.ProvideApplication(cfg, logger, postgresDB, clickHouseDB, engine, handlers, traceService, batchWriterResult, grpcComponents)
	return application, nil
}
