// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/otelguard/otelguard/internal/config"
	"github.com/otelguard/otelguard/internal/wire"
)

// Injectors from wire.go:

// InitializeApplication creates a fully-wired Application instance.
// Wire will generate the implementation of this function.
func InitializeApplication(cfg *config.Config) (*wire.Application, error) {
	logger := wire.ProvideLogger(cfg)
	postgresDB, err := wire.ProvidePostgresDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	clickHouseDB, err := wire.ProvideClickHouseConn(cfg)
	if err != nil {
		return nil, err
	}
	pool := postgresDB.DB
	healthHandler := wire.ProvideHealthHandler(pool, logger)
	userRepository := wire.ProvideUserRepository(pool)
	authService := wire.ProvideAuthService(userRepository, logger, cfg)
	organizationRepository := wire.ProvideOrganizationRepository(pool)
	projectRepository := wire.ProvideProjectRepository(pool)
	orgService := wire.ProvideOrgService(organizationRepository, projectRepository, userRepository, logger, cfg)
	authHandler := wire.ProvideAuthHandler(authService, orgService, cfg, logger)
	orgHandler := wire.ProvideOrgHandler(orgService, logger)
	conn := clickHouseDB.Conn
	traceRepository := wire.ProvideTraceRepository(conn)
	batchWriterResult := wire.ProvideBatchWriter(conn, cfg, logger)
	samplerConfig := wire.ProvideSamplerConfig(cfg)
	traceService := wire.ProvideTraceService(traceRepository, batchWriterResult, samplerConfig, cfg, logger)
	traceHandler := wire.ProvideTraceHandler(traceService, logger)
	otlpHandler := wire.ProvideOTLPHandler(traceService, logger)
	promptRepository := wire.ProvidePromptRepository(pool)
	promptService := wire.ProvidePromptService(promptRepository, logger)
	promptHandler := wire.ProvidePromptHandler(promptService, traceService, logger)
	guardrailRepository := wire.ProvideGuardrailRepository(pool)
	guardrailEventRepository := wire.ProvideGuardrailEventRepository(conn)
	guardrailService := wire.ProvideGuardrailService(guardrailRepository, guardrailEventRepository, logger)
	guardrailHandler := wire.ProvideGuardrailHandler(guardrailService, logger)
	annotationRepository := wire.ProvideAnnotationRepository(pool)
	annotationService := wire.ProvideAnnotationService(annotationRepository, projectRepository, userRepository, logger)
	annotationHandler := wire.ProvideAnnotationHandler(annotationService, logger)
	feedbackRepository := wire.ProvideFeedbackRepository(pool)
	feedbackScoreMappingRepository := wire.ProvideFeedbackScoreMappingRepository(pool)
	feedbackScoreMappingService := wire.ProvideFeedbackScoreMappingService(feedbackScoreMappingRepository, traceService, projectRepository, logger)
	feedbackService := wire.ProvideFeedbackService(feedbackRepository, feedbackScoreMappingService, projectRepository, userRepository, logger)
	feedbackHandler := wire.ProvideFeedbackHandler(feedbackService, logger)
	tokenizerService := wire.ProvideTokenizerService()
	pricingService := wire.ProvidePricingService()
	llmServiceImpl := wire.ProvideLLMService(logger, tokenizerService, pricingService)
	llmHandler := wire.ProvideLLMHandler(llmServiceImpl, tokenizerService, pricingService, logger)
	agentRepository := wire.ProvideAgentRepository(conn)
	agentService := wire.ProvideAgentService(agentRepository, traceRepository, logger)
	agentHandler := wire.ProvideAgentHandler(agentService, logger)
	evaluatorRepository := wire.ProvideEvaluatorRepository(pool)
	evaluationJobRepository := wire.ProvideEvaluationJobRepository(pool)
	evaluationResultRepository := wire.ProvideEvaluationResultRepository(conn)
	evaluatorService := wire.ProvideEvaluatorService(evaluatorRepository, evaluationJobRepository, evaluationResultRepository, traceRepository, llmServiceImpl, pricingService, logger)
	evaluatorHandler := wire.ProvideEvaluatorHandler(evaluatorService, logger)
	datasetRepository := wire.ProvideDatasetRepository(pool)
	datasetService := wire.ProvideDatasetService(datasetRepository, logger)
	datasetHandler := wire.ProvideDatasetHandler(datasetService, logger)
	experimentRepository := wire.ProvideExperimentRepository(pool)
	experimentService := wire.ProvideExperimentService(experimentRepository, datasetRepository, promptRepository, llmServiceImpl, evaluatorService, logger)
	experimentHandler := wire.ProvideExperimentHandler(experimentService, logger)
	handlers := wire.ProvideHandlers(healthHandler, authHandler, orgHandler, traceHandler, otlpHandler, promptHandler, guardrailHandler, annotationHandler, feedbackHandler, llmHandler, agentHandler, evaluatorHandler, datasetHandler, experimentHandler)
	engine := wire.ProvideRouter(handlers, cfg, logger)
	grpcComponents := wire.ProvideGRPCComponents(traceService, cfg, logger)
	application := wire.ProvideApplication(cfg, logger, postgresDB, clickHouseDB, engine, handlers, traceService, evaluatorService, experimentService, batchWriterResult, grpcComponents)
	return application, nil
}
